title: jbritain.github.io

github: jbritain
youtube: UCsixy16a1K_PZ2sudNt2zrQ

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-octicons

collections:
  - projects

permalink: pretty